# Generated by Django 4.2.7 on 2024-01-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Toatlamt',
            new_name='Totalamt',
        ),
    ]
