# Generated by Django 4.2.7 on 2024-01-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_order_orderdetial_payment_delete_ordertable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user')),
                ('paymentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.payment')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet')),
            ],
            options={
                'db_table': 'oderdetail',
            },
        ),
        migrations.DeleteModel(
            name='orderdetial',
        ),
    ]
