# Generated by Django 4.2.7 on 2024-01-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_orderdetail_delete_orderdetial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='paymentid',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.payment'),
        ),
    ]
